.TH sam_archive_directory_image 1 "fife_utils"
.SH NAME
 sam_archive_directory_image \- archive files to experiment archvive area and declare.

.SH SYNOPSIS
.B sam_archive_directory_image [options] --src=\fIpath\fB
.SH DESCRIPTION

This script basically makes a tarfile  backup of a directory, and stores it the experiment tape-backed area, and declares it to SAM.  It also makes, if it does not exist, a datset $USER_archive_images (with $USER replaced by your username) which lists all your archive images, and puts the path which was archvied in the metadata of the file.

It is very useful if there is a disk area in your DCache persistent, or BlueArc areas which you want to free up, but you're not sure you should throw away; you can archive it, and then remove the directory, and you can unpack it later if needed -- see sam_restore_directory_image.

Note: while you could schedule regular backups of directories with this tool and a cron job,  the incremental backup tools provided by the systems folks at the lab are far more efficient.  If you find yourself considering running a nightly or weekly backup this way, please see the \fBFNAL Site Backups\fN page  at http://computing.fnal.gov/site-backups/, and use their tools,  instead.

.SH OPTIONS
.TP
.B -h|--help
show this help message and exit
.TP
.B -v|--verbose

.TP
.B -j|--just_say
do not actually copy, just say what you would do
.TP
.B -e \fIEXPERIMENT\fB|--experiment=\fIEXPERIMENT\fB

.TP
.B -n \fINAME\fB|--name=\fINAME\fB
dataset name/tag to put in: default is
"$USER_archive_images"
.TP
.B -s \fISRC\fB|--src=\fISRC\fB
source directory to archive
.TP
.B -d \fIDEST\fB|--dest=\fIDEST\fB
override destination to archive to, default is 
/pnfs/$EXPERIMENT/archive/sam_managed_users/$USER/image/$DATE
.TP
.B -4|--nfs4
write tarfile directly via nfs4
.SH "SEE ALSO"

sam_add_dataset(1),
sam_archive_dataset(1),
sam_clone_dataset(1),
sam_condense_dataset(1),
sam_copy2scratch_dataset(1),
sam_modify_dataset_metadata(1),
sam_move2archive_dataset(1),
sam_move2persistent_dataset(1),
sam_move_dataset(1),
sam_pin_dataset(1),
sam_prestage_dataset(1),
sam_remove_location_dataset(1),
sam_restore_directory_image(1),
sam_retire_dataset(1),
sam_revert_names(1),
sam_unclone_dataset(1),
sam_validate_dataset(1)
